CREATE DATABASE IF NOT EXISTS ch4e CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE ch4e;

-- CREATE TABLE IF NOT EXISTS roles (
--   id BIGINT PRIMARY KEY AUTO_INCREMENT,
--   name VARCHAR(50) UNIQUE NOT NULL
-- );
-- INSERT IGNORE INTO roles(name) VALUES ('ROLE_USER'), ('ROLE_ADMIN');

-- CREATE TABLE IF NOT EXISTS users (
--   id BIGINT PRIMARY KEY AUTO_INCREMENT,
--   name VARCHAR(120) NOT NULL,
--   email VARCHAR(150) UNIQUE,
--   phone VARCHAR(30) UNIQUE,
--   password VARCHAR(255),
--   provider VARCHAR(20) NOT NULL DEFAULT 'LOCAL',
--   provider_id VARCHAR(255),
--   enabled TINYINT(1) NOT NULL DEFAULT 1,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- CREATE TABLE IF NOT EXISTS user_roles (
--   user_id BIGINT NOT NULL,
--   role_id BIGINT NOT NULL,
--   PRIMARY KEY (user_id, role_id),
--   CONSTRAINT fk_ur_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
--   CONSTRAINT fk_ur_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
-- );
-- SHOW TABLES;
-- CREATE TABLE IF NOT EXISTS refresh_tokens (
--   id BIGINT PRIMARY KEY AUTO_INCREMENT,
--   token VARCHAR(512) NOT NULL UNIQUE,
--   user_id BIGINT NOT NULL,
--   expiry TIMESTAMP NOT NULL,
--   CONSTRAINT fk_rt_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
-- );
-- SET FOREIGN_KEY_CHECKS = 0;

-- TRUNCATE TABLE refresh_tokens;
-- TRUNCATE TABLE user_roles;
-- TRUNCATE TABLE users;

-- SET FOREIGN_KEY_CHECKS = 1;

SELECT * FROM refresh_tokens;
-- select * from users;
